### ISSUE TITLE
Hackage documentation seems missing

### ISSUE THREAD

**Issue by andreyk0** [mbj/stratosphere#102]
https://hackage.haskell.org/package/stratosphere

OTOH stackage seems Ok
https://www.stackage.org/lts-12.13/package/stratosphere-0.24.4

Is this something that could be fixed?
It's not the end of the world but hackage is still the 1st link on Google and other tools (e.g. https://kapeli.com/dash) look there as well.

Thanks!

**Comment by jdreaver** [comment]
I've seen various scripts in the past to upload Haddock docs to Hackage directly, but I'm not sure I want to spend time re-learning how to do that automating keeping those updated. Like you said, the Stackage docs work great (and are generated very quickly in my experience).

I'll go ahead and leave this open in case someone can find a no-pain, automated solution here.

**Comment by mbj** [comment]
I think that hackage has a smaller timeout than the other services to generate the docs. This and that this library has a huge number of modules creates the situation where this timeout is overrun.

The solution will be roughly the same as #184, split the generated modules out over AWS service specific subpackages.

This will make the individual subpackages assemble docs within that assumed timeout.

**Comment by mbj** [comment]
This may likely be addressed via #207 as we now have a package per AWS service, the next hackage upload (will be a while) should render the documentation.

**Comment by mbj** [comment]
I'm closing this as I've confirmed it was a size issue, given #207 was merged this issue will be gone on the next release.
