### ISSUE TITLE
Call for new maintainer

### ISSUE THREAD

**Issue by pbrisbin** [mbj/stratosphere#186]
At Freckle, we are moving away from the tooling that uses Stratosphere and are looking for someone to take over maintenance of this package. It will likely need significant updates, particularly to address #185 and #184.

@jdreaver as the original author, would you like to take over ownership of this package?

Tagging other historical contributors,

- @ababkin
- @MichaelXavier
- @timmytofu
- @mbj
- @amar47shah
- @5outh
- @Gosha
- @Znack
- @louoso
- @kelizarov

If a new maintainer is found we would,

- Transfer to your GitHub user/org
- Add your identity as a Hackage maintainer and remove ourselves

**Comment by jdreaver** [comment]
Hey @pbrisbin! I don't use this either anymore, so if we can't find a maintainer I think we should just archive this repo.

Also, I think I have the Hackage ownership bits, so if someone wants to step up and maintain this package I can transfer those as well.

**Comment by pbrisbin** [comment]
:wave: sounds good!

I'll leave this issue open for a few weeks then proceed with abandoning :smiling_face_with_tear:

**Comment by mbj** [comment]
I'd generally be interested, I've solved #185 https://github.com/freckle/stratosphere/compare/master...mbj:add/aeson-2-support (not PR ready, I'd split the commits etc). And verified that #184 is a module count issue with `stack` and `ghc` hence to unblock my teams I created a "redux" branch where I removed services we do not use to get it to compile.

A solution for #184 may be to break this package up into subpackages (ala `amazonka`) which allows users to pull the services they need (which will also reduce compile times), as I expect 99% of all modules are usually "unused". This would be a breaking change, as I'd not be able to afford to make backwards compatibility on my own time.

Before I put in an official bid, can I ask where you are moving to at Freckle when it comes to COI / DSL?

**Comment by jdreaver** [comment]
I'll let Pat respond for Freckle, but for context I now work at Stripe and we use Terraform generally (and not Haskell).

One thing I'll note for future maintainers is the last few times I updated the JSON model file from CloudFormation, I realized the document doesn't follow their published schema :cry: I had to manually edit the doc for codegen to work.

**Comment by mbj** [comment]
> I had to manually edit the doc for codegen to work.

I'm aware of this, I have a (never published) dhall version of stratopshere.

**Comment by jdreaver** [comment]
Oh that's neat! In that same vein, if I were to recreate something like `stratosphere` today, I would build it on top of Dhall or [CUE](https://cuelang.org/) and just ship the generated JSON to the CloudFormation API.

**Comment by mbj** [comment]
OT on dhall / external language:

I use some extensive metadata driven generation of stratopshere EDSL, which I also re-use in my apps. This way for example there cannot be "unreferencable" ENV variables in lambda/ECS.

Once I found this property to be super useful, I stopped my dhall approaches to avoid impedance mismatch.

So I'd have a domain specific sum type like:

```
data ServiceTypes = A | B | C
  deriving stock (...., Enum)
```

And than iterate over that sum type in my stratopshere templates to generate out the various manifestation of lambda functions etc.

This, yes: would be possible via `dhall` (bridging the definition) but its more impedance mismatch than using HS native.

**Comment by jdreaver** [comment]
Ah that makes sense. I think the canonical solution to bridge the gap would be to define `ServiceTypes` in Dhall/CUE/whatever and then codegen that into a Haskell sum type. I can see why that could be a massive PITA though and why just embedding in Haskell is simpler :smile:

**Comment by pbrisbin** [comment]
> may be to break this package up into subpackages

Yeah, that seems like the right solution to me.

> can I ask where you are moving to at Freckle when it comes to COI / DSL?

We've learned that working with plain CloudFormation Templates (in yaml) is best for us:

- Able to actually use in-the-wild docs and examples without having to translate to the DSL
- Familiar with AWS, but not Haskell, is all you need to contribute
- Tools like `cfn-lint` have been really useful, and actually catch a lot of bugs our types were catching before
- Able to take Stacks not under IaC and "capture" them by simply copying the template and parameters
- Not doing things in a real programming language has been a good forcing function to keep things simple and declarative (if sometimes repetitive)

The last point is the reason we're _not_ moving to CDK, which is probably where most (non-terraform) teams end up.

The only real hurdle we had to climb was encoding the "layer up", so to speak, in the IaC system. You can commit the Templates sure, but then where do you commit the fact that they're deployed as Stacks named X with Parameters Y and Z in some Account/Region? For that, we implemented a relatively simple tool called [Stackctl](https://github.com/freckle/stackctl). I plan to formally announce it via our blog in the coming weeks, so beware it's not totally polished yet.

> I had to manually edit the doc for codegen to work.

If I understand correctly, a lot of Amazonka is actually a system for coding "overrides" into the generation process. So this seems to be a pattern.

**Comment by mbj** [comment]
> ut then where do you commit the fact that they're deployed as Stacks named X with Parameters Y and Z in some Account/Region? For that, we implemented a relatively simple tool called [Stackctl](https://github.com/freckle/stackctl). I plan to formally announce it via our blog in the coming weeks, so beware it's not totally polished yet.

I've never announced it but I have an equivalent (building on top of `stratosphere` and `amazonka`): `stack-deploy`. 

It works via providing the concept of an "instance-spec" tying up the template + parameters into a lifecycle.

Its here: https://github.com/mbj/mhs/tree/main/stack-deploy (glorious docs, thats sarcastic).

Glad to see that we have parallel evolution here.

**Comment by mbj** [comment]
So overall my plans for stratosphere would be:

* Get it closer to amazonka-2 (also in field naming, they made lots of progress there)
* Break up into subpackages.

I'd probably not do any maintenance releases of the current 0.59.1 but aeason-2 support, or similar ecosystem wide changes, that are relatively easy to fix.

Lets wait a bit for other to chime in before coming to a conclusion here.

**Comment by pbrisbin** [comment]
> It works via providing the concept of an "instance-spec" tying up the template + parameters + instance name: into a lifecycle.

Ah yes, that sounds exactly like [what we have](https://github.com/freckle/stackctl/blob/main/doc/stackctl.1.md#stack-specifications), which was inspired by [CloudGenesis](https://medium.com/@rmmeans/gitops-for-cloudformation-announcing-cloudgenesis-55bbc44495b6).

I think this gap is mostly filed by CDK, but if you exclude coding in an actual programming language, something along these lines is pretty much the only place you could end up. It's also a very fun problem to hack on!

> Lets wait a bit for other to chime in before coming to a conclusion here.

Sounds good!

> So overall my plans for stratosphere would be:

Your plan sounds good to me, and appreciate the transparency, but just to be overly-clear we'd be transferring ownership for you to do as you wish, no strings attached :)

**Comment by mbj** [comment]
> we'd be transferring ownership for you to do as you wish, no strings attached :)

Yeah, but it may be someone else can offer better community wide support than me.

**Comment by mbj** [comment]
RE stack-deploy etc:

I found it very useful to have a "frontend" CLI that provides 0 dynamic ability, and the option to extend it with "implicit parameters" generated at runtime.

In my case I can do some fun stuff like hashing secrets to trigger invalidation of CF definitions allowing me to stay even more declarative than standard CF.

**Comment by mbj** [comment]
I personally prefer CF over terraform as AWS integrates better and provides me the global state handler / lock manager. Avoiding the need to deploy that first.

**Comment by pbrisbin** [comment]
Yeah ditto that. Maybe I can convince you to use (and contribute) to Stackctl one day, after I get it properly announced.

**Comment by mbj** [comment]
I do not ever want to maintain `.yaml` based templates again. Even with linters, these are "gah" ;)

**Comment by pbrisbin** [comment]
Alright, it has been two weeks with no movement, so I think we're good to transfer to @mbj.

If there are no objections, I will:

1. Transfer this repository to `mbj/stratosphere`
2. Ask @jdreaver to add @mbj as a Hackage maintainer

@mbj can you confirm, and let David know your Hackage username?

**Comment by mbj** [comment]
@pbrisbin, @jdreaver  My hackage user name is `mbj`.

You want me to remove existing hackage users on the package later, or stay as a backup? I'm fine with either.

**Comment by jdreaver** [comment]
Hey @mbj, I just added you! I'm the only other maintainer. Feel free to keep me on as a backup if you want, totally up to you.

https://hackage.haskell.org/package/stratosphere/maintainers/

**Comment by jdreaver** [comment]
I should also mention, all of the license/copyright bits say

> Copyright (c) 2016 David Reaver

since I originally made this in my spare time under my own Github account, but transferred it to the Freckle Github org at the behest of the CTO at the time so we could expand our open source footprint. I've never dealt with transferring copyright bits like that. Should we change it from "David Reaver" to "Stratosphere maintainers"? Does it even matter?

**Comment by mbj** [comment]
I've limited experience in the field, so do not take me as an authoritative source:

You accepted contributors so its all "mixed" up at this point.

This means anyone in [the contributors](https://github.com/freckle/stratosphere/graphs/contributors) list would have to agree to a copyright re-assignment (or remove contributions). This should not be the way to go.

Instead I'd argue to do change it to `Stratosphere maintainers` which is the closed approximation without listing everyone who ever contributed, as they own the individual contribution.

**Comment by mbj** [comment]
>  Feel free to keep me on as a backup if you want, totally up to you.

will keep you on for the time being, but may later remove you if we had no interactions for a longer time. I do the same for my ruby OSS where I have co-maintainers, if some years pass I reduce credential exposure.

**Comment by pbrisbin** [comment]
Just tried the transfer,

>  mbj/stratosphere already exists and You can only transfer a repository from an organization to yourself at this time 

I think you have to remove your fork first @mbj, then I'll try again. In the meantime, I'm going to transfer it from the org to myself, so that I can then transfer it to you.

**Comment by mbj** [comment]
give me a day, I've to first change the references to my fork at work to a copy of my fork.

**Comment by pbrisbin** [comment]
Would it be faster to merge whatever you have in your fork upstream (now pbrisbin/stratosphere) then (quickly) delete-and-transfer? Anything references mbj/stratosphere would get the same code before/after.

**Comment by mbj** [comment]
I'm almost done my side, so `mbj/stratosphere` is free now. I'll re-push my branches (no need to merge) there to keep my builds passing.

my branches are not ready to be merged as I hacked the generator output vs fixing it (For aeson-2).

**Comment by mbj** [comment]
To be clear, you can move to `mbj/stratosphere` now, I'll handle it from there.

**Comment by pbrisbin** [comment]
> mbj already has a repository in the pbrisbin/stratosphere network 

:thinking: unclear what this means and how to get around it.

I might give it a day and try again -- all this deletion and transfer may need time to be eventually consistent in GitHub systems.

**Comment by mbj** [comment]
@pbrisbin My moved repository is a fork of yours, this will not self resolve, I'll "unfork" it. Sec.

**Comment by mbj** [comment]
done. (via deletion of my fork and re-pushing without fork relationship). please retry. Sorry for not anticipating this, I do not do that operation every day.

**Comment by pbrisbin** [comment]
Transfer in progress!

**Comment by mbj** [comment]
Accepted, and its now under my GH account. Thx. Closing this issue.
