### ISSUE TITLE
Support newer versions of nodejs aws lambda runtimes

### ISSUE THREAD

**Issue by joelmccracken** [mbj/stratosphere#195]
The newest one listed, node12x, is about to be EOL. I'm working on a patch to add some new ones.

**Comment by mbj** [comment]
Hi joel, I started to work on stratosphere again. I expect an updated release before new year.

**Comment by mbj** [comment]
@joelmccracken ended up to work on this in the new year, please check out: https://github.com/mbj/stratosphere/pull/203 which is a more "universal" albeit "less pretty" solution to the issue. I'll close this ticket with #203 merged, but a release for #203 state will take a while as I've got some more breaking changes to introduce.

**Comment by mbj** [comment]
@joelmccracken You could always use `OtherRuntimes "yourNewLiteral"` in the released versions. you should not be blocked on the enum members (I removed anyway).
